create table if not exists public.leaderboard (
    id bigint generated by default as identity primary key,
    username text not null,
    score integer not null,
    time_seconds integer not null,
    hints_used integer not null default 0,
    created_at timestamptz not null default now()
);

alter table public.leaderboard enable row level security;

drop policy if exists "Public can view leaderboard" on public.leaderboard;
create policy "Public can view leaderboard" on public.leaderboard
for select to anon using (true);

drop policy if exists "Public can submit scores" on public.leaderboard;
create policy "Public can submit scores" on public.leaderboard
for insert to anon with check (
    char_length(username) between 1 and 30
    and score >= 0
    and time_seconds >= 0
    and hints_used >= 0
);
